services:  
 mysql-food:
  image: mysql:latest
  ports:
    - 3308:3306
  volumes:
    - mysql_food_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 mysql-animal:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_animal_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123

 mongo-enclosure:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_enclosure_data:/data/db
   
 food-service:
  depends_on:
    - mysql-food
  image: natanvanbraeckel/food-service:latest
  ports:
    - 8081:8081
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-food
   MYSQL_DB_PORT: 3308

 animal-service:
  depends_on:
    - mysql-animal
    - food-service
  image: natanvanbraeckel/animal-service:latest
  ports:
    - 8082:8082
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-animal
   MYSQL_DB_PORT: 3307
   FOOD_SERVICE_BASEURL: food-service:8081

 enclosure-service:
  depends_on:
    - mongo-enclosure
    - animal-service
  image: natanvanbraeckel/enclosure-service:latest
  ports:
    - 8080:8080
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-enclosure
   ANIMAL_SERVICE_BASEURL: animal-service:8082

 api-gateway:
  depends_on:
    - food-service
    - animal-service
    - enclosure-service
  image: natanvanbraeckel/api-gateway-new:latest
  ports:
    - 8083:8083
  environment:
   FOOD_SERVICE_BASEURL: food-service:8081
   ANIMAL_SERVICE_BASEURL: animal-service:8082
   ENCLOSURE_SERVICE_BASEURL: enclosure-service:8080

volumes:
 mysql_food_data:
 mysql_animal_data:
 mongodb_enclosure_data: