apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: enclosure-service
  name: enclosure-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: enclosure-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: enclosure-service
    spec:
      containers:
        - env:
            - name: ANIMAL_SERVICE_BASEURL
              value: animal-service:8082
            - name: MONGODB_HOST
              value: mongo-enclosure
            - name: MONGODB_PORT
              value: "27017"
          image: natanvanbraeckel/enclosure-service-arf:latest
          name: enclosure-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
