apiVersion: v1
kind: Service
metadata:
  labels:
    ede.natanvb: animal-service
  name: animal-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    ede.natanvb: animal-service
status:
  loadBalancer: {}
