apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    ede.natanvb: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      ede.natanvb: api-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        ede.natanvb: api-gateway
    spec:
      containers:
        - env:
            - name: ANIMAL_SERVICE_BASEURL
              value: animal-service:8082
            - name: ENCLOSURE_SERVICE_BASEURL
              value: enclosure-service:8080
            - name: FOOD_SERVICE_BASEURL
              value: food-service:8081
          image: natanvanbraeckel/api-gateway-frontend2:latest
          name: api-gateway
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}
