apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    ede.natanvb: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
      nodePort: 30001
  selector:
    ede.natanvb: api-gateway
  type: NodePort
status:
  loadBalancer: {}
