apiVersion: v1
kind: Service
metadata:
  labels:
    ede.natanvb: food-service
  name: food-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    ede.natanvb: food-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ede.natanvb: food-service
  name: food-service
spec:
  replicas: 1
  selector:
    matchLabels:
      ede.natanvb: food-service
  strategy: {}
  template:
    metadata:
      labels:
        ede.natanvb: food-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB_HOST
              value: mysql-food
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_PORT
              value: "3308"
            - name: MYSQL_DB_USERNAME
              value: root
          image: natanvanbraeckel/food-service-update:latest
          name: food-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
