apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-enclosure
  name: mongo-enclosure
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-enclosure
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-enclosure
    spec:
      containers:
        - image: mongo:latest
          name: mongo-enclosure
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-enclosure-data
      restartPolicy: Always
      volumes:
        - name: mongodb-enclosure-data
          persistentVolumeClaim:
            claimName: mongodb-enclosure-data
status: {}
