apiVersion: v1
kind: Service
metadata:
  labels:
    ede.natanvb: mongo-enclosure
  name: mongo-enclosure
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    ede.natanvb: mongo-enclosure
status:
  loadBalancer: {}
