apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ede.natanvb: mongodb-enclosure-data
  name: mongodb-enclosure-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
