apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ede.natanvb: mongo-enclosure
  name: mongo-enclosure
spec:
  replicas: 1
  selector:
    matchLabels:
      ede.natanvb: mongo-enclosure
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ede.natanvb: mongo-enclosure
    spec:
      containers:
        - image: mongo:latest
          name: mongo-enclosure
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-enclosure-data
      restartPolicy: Always
      volumes:
        - name: mongodb-enclosure-data
          persistentVolumeClaim:
            claimName: mongodb-enclosure-data
status: {}
