apiVersion: v1
kind: Service
metadata:
  labels:
    ede.natanvb: mysql-animal
  name: mysql-animal
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    ede.natanvb: mysql-animal
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ede.natanvb: mysql-animal
  name: mysql-animal
spec:
  replicas: 1
  selector:
    matchLabels:
      ede.natanvb: mysql-animal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        ede.natanvb: mysql-animal
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: abc123
          image: mysql:latest
          name: mysql-animal
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-animal-data
      restartPolicy: Always
      volumes:
        - name: mysql-animal-data
          persistentVolumeClaim:
            claimName: mysql-animal-data
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ede.natanvb: mysql-animal-data
  name: mysql-animal-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
