apiVersion: v1
kind: Service
metadata:
  labels:
    ede.natanvb: mysql-animal
  name: mysql-animal
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    ede.natanvb: mysql-animal
status:
  loadBalancer: {}
