apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ede.natanvb: mysql-food-data
  name: mysql-food-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
